apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: my-statefulset
spec:
  serviceName: my-service
  replicas: 3
  selector:
    matchLabels:
      app: my-stateful-app
  template:
    metadata:
      labels:
        app: my-stateful-app
    spec:
      containers:
      - name: my-stateful-container
        image: registry.example - FORBIDDEN - /my-stateful-image:latest
        imagePullPolicy: Always
      imagePullSecrets:
      - name: my-registry-secret
