# ... (Deployment) ...
      containers:
      - name: my-webserver-container
        image: nginx:latest
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
        # ... (остальные части) ...
