---
apiVersion: v1
kind: Secret
metadata:
  name: my-webserver-db-secret
type: Opaque # Тип Opaque подходит для любых произвольных данных
data:
  DATABASE_URL: c2VjcmV0LWRhdGFiYXNlLVVSTCA9IGpkaWM6bXNxbDovL215ZGI6MzMzNi9teWRhdGFiYXNl # base64 encoded "secret-database-URL = jdbc:mysql - FORBIDDEN - mydb:3336/mydatabase"
  DB_USERNAME: ZGJ1c2Vy # base64 encoded "dbuser"
  DB_PASSWORD: cGFzc3dvcmQ= # base64 encoded "password"

---
apiVersion: v1
kind: Secret
metadata:
  name: my-webserver-api-key-secret
type: Opaque
stringData: # stringData - удобен для небольшого числа секретов, хранит данные в виде строк.
  API_KEY: "abcdef123456"

---
apiVersion: v1
kind: Secret
metadata:
  name: my-webserver-ssl-cert
type: kubernetes.io/tls # Специальный тип для сертификатов SSL
data:
  tls.crt: <base64-encoded-certificate>  # base64-encoded certificate
  tls.key: <base64-encoded-private-key> # base64-encoded private key

---
apiVersion: v1
kind: Secret
metadata:
  name: my-webserver-docker-secret
type: kubernetes.io/dockercfg # Специальный тип для учетных данных Docker
data:
  .dockercfg: <base64-encoded-docker-config-json> # base64-encoded Docker config JSON

---
# Secret для настроек базы данных
apiVersion: v1
kind: Secret
metadata:
  name: my-webserver-db-secret                            # <-- 1 -->
stringData:                                               # тип секета, в данном случае это строка 
  database_url: "jdbc:mysql - FORBIDDEN - mydb:3306/mydatabase?user=dbuser&password=dbpassword"


--- 
# Deployment (изменения в части containers и volumes)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-webserver
spec:
  # ... (остальные части Deployment)
      containers:
      - name: my-webserver-container
        image: my-webserver-image
        envFrom:                                          # данные передаются внутрь контейнеров в виде переменных окружения
        - secretRef:
            name: my-webserver-db-secret                  # <-- 1 -->
        volumeMounts:
        - name: server-config-volume
          mountPath: /etc/my-webserver/server
      volumes:
      - name: server-config-volume
        configMap:
          name: my-webserver-server-config
